---
abstract: 'Parse a Carp stack trace into an array of caller information, while redacting sensitive function parameters out.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
  - 'Kate Kirby <kate@cpan.org>'
build_requires:
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Carp-Parse-Redact
provides:
  Carp::Parse::CallerInformation::Redacted:
    file: lib/Carp/Parse/CallerInformation/Redacted.pm
    version: v1.1.3
  Carp::Parse::Redact:
    file: lib/Carp/Parse/Redact.pm
    version: v1.1.3
requires:
  Carp: 0
  Carp::Parse: 0
  Data::Dump: 0
  Data::Validate::Type: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=carp-parse-redact
  homepage: https://metacpan.org/release/Carp-Parse-Redact
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/katekirby/Carp-Parse-Redact.git
version: v1.1.3
